server:
  port : 9193
  
spring:
  application:
    name: LMSBookService
  datasource:
    url: jdbc:mysql://localhost:3306/lmssystem
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQLDialect

        
jwt:
  secret : U3VwZXJTZWNyZXRLZXlGb3JKd3RUb2tlbjEyMzQ1Njc4OTAxMjM0NTY=
  accessToken:
    expiration : 600000     # 10 minutes
  refreshToken:
    expiration : 1800000   # 30 minutes

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Eureka server URL
    register-with-eureka: true
    fetch-registry: true