server:
  port : 9192
  
spring:
  application:
    name: LMSMemberService
  datasource:
    url: jdbc:mysql://localhost:3306/lmssystem
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQLDialect
